### ISSUE TITLE
libpython3.10.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by ithakaa** [YoRyan/mailrise#15]
I have deployed your docker and I am seeing the below error

`/usr/local/bin/python: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

**Comment by YoRyan** [comment]
Same issue as somebody reported in #2. He ultimately solved his problem by moving to another Docker host.

Could I ask which platform you're running on? I've just tested the latest image (`b28285b16b86876ac7a41e5f555934ddb84e8f16722183916c3e3e064234f178`) on Ubuntu 20.04 amd64 and Docker Desktop for WSL2 and it worked flawlessly on both hosts.

```
$ sudo docker run -it --rm yoryan/mailrise:latest --help
usage: mailrise [-h] [--version] [-v] [-vv] CONFIG

An SMTP gateway for Apprise notifications

positional arguments:

  CONFIG               path to configuration file

options:
  -h, --help           show this help message and exit
  --version            show program's version number and exit
  -v, --verbose        set loglevel to INFO
  -vv, --very-verbose  set loglevel to DEBUG
```

**Comment by ithakaa** [comment]
I am running it on Unraid Version: 6.9.2

**Comment by barefooter22** [comment]
It looks like I'm also seeing this issue.  I think it's because the Python release for me on Ubuntu 18.04 is Python 3.6.  I'm taking a look at getting 3.10 installed and see if that fixes it

**Comment by YoRyan** [comment]
I suspect the underlying issue is that the official Docker image for Python, which includes version 3.10, is too new to run on older hosts, such as Unraid and Ubuntu 18.04.

I've added a Dockerfile for Python 3.8 and a new tag, `latest-3.8`. This image should hopefully run in these older hosts.

> It looks like I'm also seeing this issue. I think it's because the Python release for me on Ubuntu 18.04 is Python 3.6. I'm taking a look at getting 3.10 installed and see if that fixes it

The Python version installed on your host OS has no relation to the version used in the Docker image.
