### ISSUE TITLE
Question - Preserving look and feel of notifications

### ISSUE THREAD

**Issue by samcro1967** [YoRyan/mailrise#17]
Is it possible to preserve the look and feel of a notification so that it looks the same going to directly to Gotify and Discord?  When I send them through mailrise, they do not look the same.

Application --> Mailrise -- Gotify 
![mailrise](https://user-images.githubusercontent.com/2319445/170989008-26fbe80d-0619-43ed-a9a6-902db8e8e6b8.jpg)

Application directly to Gotify
![gotify](https://user-images.githubusercontent.com/2319445/170988970-9b368547-1a23-464e-b8b5-b9f3208b97ef.jpg)

**Comment by YoRyan** [comment]
Parsing emails is always a tricky business. Some applications produce complicated multipart messages that aren't easy to reduce to a single subject line and message body. If you could supply a sample email, that would be a huge help to understanding this particular case.

One thing that raises my eyebrows is the "{{ service_id }}" token in the email message, which looks like a template that failed to render?

**Comment by samcro1967** [comment]
The issue with the service sending the messages has been updated so that the variables are properly expanded before being sent to mailrise.  Waiting for a new message to now come across to see if the issue persists.  Realized the service had an issue when I sent messages directly to my Gmail account and saw the same formatting.

**Comment by samcro1967** [comment]
Issue was with the application sending the emails.  Thanks for your help in pointing me in the right direction.

![image](https://user-images.githubusercontent.com/2319445/175551779-29d91ffc-b5a8-427e-8e2d-6f9ab7cb8669.png)
