### ISSUE TITLE
Feature request - enable smtp auth

### ISSUE THREAD

**Issue by kaislaoja** [YoRyan/mailrise#22]
I would like to see a way to use some kind of authentication when you send emails to the mailrise. At least some type of local username/password list in the configuration file or maybe even a LDAP(S) integration if it can be implemented easily.

I know that this is meant to be used in a private network where there shouldn't be unauthorised access, but I still would want to use authentication.

**Comment by YoRyan** [comment]
Basic authentication, at least, should [be easy](https://aiosmtpd.readthedocs.io/en/latest/auth.html).

**Comment by ksurl** [comment]
it would help with applications that don't have a no-auth smtp config option as well.

**Comment by YoRyan** [comment]
> it would help with applications that don't have a no-auth smtp config option as well.

Yes, that's a good point. Basic authentication is now available in the latest tip.

**Comment by ksurl** [comment]
works great. I had to dig into the commit to find the syntax in the test authenticator mockup. 

```
smtp:
  auth:
    basic:
      username: password
```

**Comment by ksurl** [comment]
It does not pick up config changes while running anymore? I have to restart for it to update. no output in the log either from `docker logs mailrise`

**Comment by YoRyan** [comment]
Mailrise never had hot reloads; you'd always have to restart the container to pick up any config changes.
