### ISSUE TITLE
Catch all config option and wildcard options

### ISSUE THREAD

**Issue by madhogs** [YoRyan/mailrise#23]
Hi,

Is it possible to add the ability for mailrise to forward notifications without specifying specific addresses?
Eg. I was thinking a catch-all such as:
```
configs:
  *:
    urls:
      - signal://example.com:8080/+1234567890
```
And/Or a wildcard option for a domain like:
```
configs:
  *@example.com:
    urls:
      - signal://example.com:8080/+1234567890
```

Just something I thought would be useful for my use case where I am the only user and using mailrise to forward any/all notifications from local services. Not sure if this has other implications which make this a bad idea.

**Comment by YoRyan** [comment]
Good idea. Implemented with fnmatch!

You can pattern match with both the username and the domain:

```yaml
configs:
  "*@example.com":
    urls:
      - signal://example.com:8080/+1234567890
```

`*` is a reserved character in YAML, so you have to use quotes. Also, `"*"` will get expanded to `"*@mailrise.xyz"`, so to match against every domain, use `"*@*"`. 👍

**Comment by madhogs** [comment]
This is great, thank you :-)
