### ISSUE TITLE
How to use certificates without root user

### ISSUE THREAD

**Issue by madhogs** [YoRyan/mailrise#25]
This isn't so much an issue with mailrise as it is more of a question in how to get what I would assume is a common workflow working.

I would like to use tls with mailrise. Currently I have a caddy docker container configured to get certificates for any apps on my server. Caddy is very useful as it auto renews the certificates.

For other apps using tls I map the caddy volume containing the certificates to the app in question, it then can use the certs by specifying the filepath to them.

This doesn't work however for mailrise as the caddy certificates are owned by root and mailrise therefore cannot access them as it does not have permission.

I have tried to run mailrise as root, but it doesn't work as the files are installed under the mailrise user, caddy needs to run as root so it can access privileged ports. There also doesn't seem to be any option to change file ownership when mapping volumes in docker.

Just wondering if you have any suggestions or have come across this before?

**Comment by YoRyan** [comment]
Yeah, the `tls` options are basically there because they're part of aiosmtpd, and there are no provisions for handling renewals or crossing permissions boundaries.

I personally let Traefik handle TLS for me, and I've just added a sample configuration to the readme to demonstrate this. I believe Caddy only supports HTTP traffic, so it will not be able to wrap ordinary TCP like Traefik can.

**Comment by YoRyan** [comment]
Another option, to retain your existing workflow, would be to build your own Mailrise image that runs as root.

```dockerfile
# first stage
FROM python:3 AS builder
WORKDIR /code
COPY . .
RUN pip install --user --no-cache-dir --no-warn-script-location .

# second stage
FROM python:3-slim
COPY --from=builder /root/.local/ /root/.local/
ENV PATH=/root/.local/bin/:$PATH
EXPOSE 8025
ENTRYPOINT ["mailrise"]
CMD ["/etc/mailrise.conf"]
```

**Comment by madhogs** [comment]
Ah sorry, this really should have been a discussion, not an issue!

Thank you for the build example, that looks like a good solution, I will give that a go.

Thanks again :smile:
