### ISSUE TITLE
Handle docker signals

### ISSUE THREAD

**Issue by bt90** [YoRyan/mailrise#44]
Judging by the ~10s it takes to restart the container, the Mailrise process is not handling the incoming SIGTERM signal.

https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop

https://docs.python.org/3/library/signal.html

**Comment by YoRyan** [comment]
Added dumb-init to the image so that the signals will work. There is no longer a 10-second pause.

**Comment by bt90** [comment]
Wouldn't a signal handler be easier? Pulling in an init system for a single process docker image sounds a bit like an overkill?

https://stackoverflow.com/a/31464349/16580522

**Comment by YoRyan** [comment]
Oops, just tested it, turns out https://github.com/YoRyan/mailrise/commit/1b83eec3152c2774774ec8fdcdd9ecea092f7986 was sufficient to respond to SIGINT properly. I've undone that commit that added dumb-init. 👍
