### ISSUE TITLE
Publish images to GHCR 

### ISSUE THREAD

**Issue by onedr0p** [YoRyan/mailrise#45]
Dockerhub has a rate limit of 100 pulls/6 hours and is continuing to make decisions that aren't on the best interest to FOSS. It would be great if you could push the docker image to GHCR as well. It should only be a few extra lines in your workflow file. Thanks!

**Comment by YoRyan** [comment]
I'm all for more choices, even if that does mean splitting the download statistics. 😁

**Comment by onedr0p** [comment]
Beautiful, statistics are overrated anyways 😄  You have no idea how easy it is to hit those rate limits when spinning up a Kubernetes cluster that has over 270 pods running in it. Every bit helps.

**Comment by YoRyan** [comment]
I'm flattered that you find Mailrise a useful component for so many pods!

**Comment by onedr0p** [comment]
Oh I'm only running one instance of mailrise with 3 replicas (stateless yay). I was talking about my whole kubernetes cluster as a whole.
