### ISSUE TITLE
Can not get docker to start

### ISSUE THREAD

**Issue by photomatix18** [YoRyan/mailrise#50]
Hello!

I can not get the docker image to run. I'm getting this error in the log:

`/usr/local/bin/python: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory`

Is there something I'm doing wrong?

**Comment by YoRyan** [comment]
Could I get some information on the hardware/software stack of the host?

You can try the -buster images. They might be better behaved with older/more obscure versions of Docker.

**Comment by photomatix18** [comment]
I'm running unRAID 6.11.5 and Docker 20.10.21.

I tried the lastest and stable versions along with the buster variant and
got the same error.

Let me know if you need any additional information!

**Comment by katosabi** [comment]
Are you running this via docker run or compose? Can you share the command/compose you're using?

Is the error inside the container or the host system?

**Comment by photomatix18** [comment]
I've only tried with docker run so far. unRAID uses a form of templating for docker run so there are certain envs it adds. I haven't mapped any ports yet, but of course, those will be needed once I get the container to run.
```
docker run
  -d
  --name='Mailrise'
  --net='bridge'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="Mailrise"
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/appdata/mailrise/':'/etc':'rw' 'yoryan/mailrise:stable'
```
The error is inside the container. It stops running right after starting it. 

I plan to try docker-compose later today when I get some time.

**Comment by katosabi** [comment]
I'm by no means a Docker expert, but I do see you're mounting a folder to
/etc inside the container; mailrise works for me with
/path/to/mailrise.conf:/etc/mailrise.conf

**Comment by photomatix18** [comment]
Nor am I! 😬I wondered about that though. I may have to use compose because I'm not aware of a way to map just a file in unRAID's docker UI. I tried but the UI changed it to a directory.

**Comment by katosabi** [comment]
Try just removing it and see if the container starts, at least that'll tell
you if that's the issue. I have a feeling it is because /etc contains a lot
of stuff.

**Comment by photomatix18** [comment]
I tried that yesterday and got
```usage: mailrise [-h] [--version] [-v] [-vv] CONFIG
mailrise: error: argument CONFIG: can't open '/etc/mailrise.conf': [Errno 2] No such file or directory: '/etc/mailrise.conf'
```
But you might be on to something because that error looks like it's coming from the mailrise service, which means it's running. 

@YoRyan would it be possible for the dockerfile to direct the config file to a dedicated directory (/config rather than /etc) so the whole directory can be passed through? Rather than passing just a file through. This seems to be the norm for most containers that I use. I can't recall using any that want individual files passed from the host although I'm sure there are others.

**Comment by photomatix18** [comment]
With compose I'm getting
`CRITICAL:mailrise.skeleton:Error loading configuration file: 'configs' node not a mapping`

This is pretty bizarre. I'm definitely not as familiar with compose so I very well could have missed something simple. Here's my compose file:

```
version: '2.1'

services:
  mailrise:
    container_name: mailrise
#    restart: unless-stopped
    image: yoryan/mailrise:stable
    ports:
      - 8025:8025
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/user/appdata/mailrise/mailrise.conf:/etc/mailrise.conf
```

**Comment by katosabi** [comment]
Your docker compose yaml looks right, can you post your mailrise.conf?
(redact what you need to)

**Comment by photomatix18** [comment]
I just threw in a sample config. I haven't really wrapped my head around how the config works.

```
#
# Minimal Configuration Example
#

# Define your URLs
urls:
  # Either on-line each entry like this:
  - json://localhost
  - xml://localhost

  # Or add a colon to the end of the URL where you can optionally provide
  # over-ride entries.  One of the most likely entry to be used here
  # is the tag entry.  This gets extended to the global tag (if defined)
  # above
  - windows://:
   # 'tag' is a special keyword that allows you to associate tags with your
   # services:
    - tag: desktop
```

You suppose that's the issue?

**Comment by katosabi** [comment]
You need to start the mailrise.conf with `configs:`, like below

```
configs:

  pve:
    urls:
      - discord://webhook_stuff
      
smtp:
  auth:
    basic:
      username: password
```

I think you also need a name above `urls:` in your config. 

In my config, if I send an email to pve.mailrise.xyz, it will then forward it to my discord webhook and ultimately my discord server. If I wanted to send it to another address like other_server.mailrise.xyz, I'd have to configure another section along with whatever service I wanted to send it to.

```
  other_server:
    urls:
      - discord://other_webhook_stuff
```

**Comment by YoRyan** [comment]
> @YoRyan would it be possible for the dockerfile to direct the config file to a dedicated directory (/config rather than /etc) so the whole directory can be passed through? Rather than passing just a file through. This seems to be the norm for most containers that I use. I can't recall using any that want individual files passed from the host although I'm sure there are others.

I did not know it was impossible to pass through a file in Unraid. To change the configuration file path, you need only add a custom argument to the container (the Dockerfile default is `/etc/mailrise.conf`). With the CLI, any arguments at the end of `docker run` after the `yoryan/mailrise` argument are passed to the container. Not sure how this is done in Unraid's UI?

```
docker run
  -d
  --name='Mailrise'
  -v '/mnt/user/appdata/mailrise/':'/etc/mailrise':'ro' 'yoryan/mailrise:stable'
  /etc/mailrise/myconfig.yml
```

Another user encountered your error, also on Unraid, probably because of this very limitation (#15). This may be worth adding to the Readme.

**Comment by katosabi** [comment]
Poking around Unraid videos (I don't see it anywhere in their documentation) it looks like you could just add `'/etc/mailrise/myconfig.yml'` to the Post Arguments field in Unraid's advanced view.

**Comment by photomatix18** [comment]
Those both seem like good solutions. I'll give both a try sometime this week and let you know!

**Comment by photomatix18** [comment]
That did it! 
![image](https://user-images.githubusercontent.com/29561215/213627061-944a5e95-b8fa-44d6-adb0-7f24f4f69ece.png)
```
docker run
  -d
  --name='mailrise'
  --net='bridge'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="mailrise"
  -l net.unraid.docker.managed=dockerman
  -p '8025:8025/tcp'
  -v '/mnt/user/appdata/mailrise/':'/etc/mailrise':'rw' 'yoryan/mailrise:stable' /etc/mailrise/config.yml
```

**Comment by katosabi** [comment]
Awesome! Glad it worked out for you.
