### ISSUE TITLE
ghcr.io image cannot be pulled by version

### ISSUE THREAD

**Issue by mfin** [YoRyan/mailrise#51]
When trying to pull the Docker image from ghcr.io, I get the following error.

```bash
❯ docker pull ghcr.io/yoryan/mailrise:1.3.0
1.3.0: Pulling from yoryan/mailrise
manifest unknown
```

**Comment by YoRyan** [comment]
Looks like I was a little overzealous in deleting old/test images. I've restored the ones needed for the stable labels.

Thanks for reporting!
