### ISSUE TITLE
Individual recipients based on emails usernames?

### ISSUE THREAD

**Issue by terion-name** [YoRyan/mailrise#56]
It is more of a team/corp usecase but nevertheless.
Let's assume we have a service, say redmine. And a chat app, say slack or matrix.
And users on all services have one-to-one username match (by internal policies or an SSO)
It would be great to send notifications to personal messages like `john.doe@mail.com` → `john.doe@matrix.local`

As far as I can see by the docs there is no way right now to do this. Am I missing something?

If not, then can this be added somehow? As I can assume there will be needed to add a `username` template variable at minimum and deal with #49. And maybe some ability to invoke functions for transforms if there is something more complicated

**Comment by YoRyan** [comment]
For complex corporate-style configurations like this, I have decided to implement pluggable Python logic with b76b164271ceacf9dbaa9184d25f47eb092e4cbc. You can now invoke Python functions to your heart's content. 👍
